- hosts: localhost
  connection: local
  tasks:
    - include: tasks/bashrcs.yml
    - include: tasks/bashmarks.yml
    - include: tasks/fzf.yml
    - include: tasks/fasd.yml
    - include: tasks/shell_colors/gruvbox_theme_for_mintty.yml
    - include: tasks/tmux.yml
    - include: tasks/tmuxinator.yml
    - include: tasks/silversearcher.yml
