- hosts: localhost
  connection: local
  tasks:
    - include: tasks/bashrcs.yml
    - include: tasks/bashmarks.yml
    - include: tasks/fzf.yml
    - include: tasks/fasd.yml
    - include: tasks/gruvbox_theme_for_mintty.yml
