---
- hosts: windows
  gather_facts: false

  tasks:
  - name: Ensure Chocolatey installed from internal repo
    win_chocolatey:
      name: chocolatey
      state: present
      source: file:///C:/Users/Dgarcia/dev/ansible/ChocolateyInstall.ps1
