- hosts: localhost
  vars:
    ansible_connection: winrm
    ansible_port: 5985
    ansible_wirm_transport: basic
    ansible_winrm_server_cert_validation: ignore
    ansible_user: ansible_user

  tasks:
     - include: tasks/packages.yml

