---
- hosts: windows
  gather_facts: false
  vars:
    em_appserver_home: C:\em\containers\hc_prototype
  vars_files:
    - '{{playbook_dir}}/passwords.yml'
      #roles:
      #  - em-ad
  tasks:
    - name: install appserver
      win_command: C:/em/projects/hc_prototype/bin/ccadmin.bat install-appserver -Dappserver.home={{em_appserver_home}}
      become: true
      become_user: winrm_user
