- hosts: localhost
  connection: local
  pre_tasks:
    - name: update repositories
      become: yes
      apt: update_cache=yes
      changed_when: False
  tasks:
     - include: tasks/main.yml
      
- hosts: localhost
  tasks:
     - include: tasks/dotfiles.yml
            
