- hosts: localhost
  connection: local
  become: yes
  pre_tasks:
    - apt_repository:
        repo: ppa:aacebedo/fasd
        state: present

    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
     - include: tasks/main.yml
     - include: tasks/dotfiles.yml
