- hosts: localhost
  connection: local
  pre_tasks:
      - name: update repositories
        apt: update_cache=yes
        changed_when: False
      become: yes
  tasks:
     - include: tasks/main.yml
     - include: tasks/dotfiles.yml
