---
- name: Add Libreoffice repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - ppa:libreoffice/ppa
    - ppa:qbittorrent-team/qbittorrent-stable

- name: "Installing Desktop Packages"
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items: "{{desktop_packages}}"

- name: Installing Synology Drive
  ansible.builtin.import_tasks: tasks/desktop/synology_drive.yml
- name: Installing Chrome
  ansible.builtin.import_tasks: tasks/desktop/chrome.yml
  when: google_chrome_repo

- name: Importing NordVPN installation task
  ansible.builtin.import_tasks: tasks/desktop/nordvpn.yml
  when: install_nordvpn
- name: Importing eams-for-linux installation task
  ansible.builtin.import_tasks: tasks/desktop/teams_for_linux.yml
  when: install_teams_for_linux
