- name: Installing nordircolors
  file: src="{{ playbook_dir }}/files/dircolors_nord" dest="{{ ansible_env.HOME}}/.dircolors" state=link force=yes
  tags: dircolors

- name: 'Source .dircolors from shell rc file'
  lineinfile:
    path: '{{myshellrc}}'
    line: eval $(dircolors ~/.dircolors)
  tags: dircolors
