- name: Installing nordircolors
  file: src="{{ playbook_dir }}/files/dircolors_nord" dest="{{ ansible_env.HOME}}/.dircolors" state=link force=yes
  tags: dircolors

- name: "Source bash_aliases from zsh"
  lineinfile:
    path: "{{myshellrc}}"
    line: eval $(dircolors ~/.dircolors)
  tags: dircolors
