- name: "Downloading dot files"
  become: yes
  become_user: dgarcia
  git: repo="https://github.com/vecin2/dotfiles.git" dest={{ansible_env.HOME}}/.dotfiles update=no
  
- name: "Link Dotfiles"
  file: src="{{ ansible_env.HOME }}/.dotfiles/{{ item }}" dest="{{ ansible_env.HOME }}/.{{ item }}" state=link force=yes
  with_items:
          - "bashrc"
          - "bash_aliases"
          - "bash_profile"
          - "profile"
          - "tmux.conf"
          - "vimrc"
          - "gvimrc"
          - "fzf.bash"
          - "gitconfig"

- name: "Create .vim folder"
  file:
    path: "{{ ansible_env.HOME}}/.vim"
    state: directory
    
- name: "Link Vim files"
  file: src="{{ ansible_env.HOME }}/.dotfiles/vim/{{ item }}.vim" dest="{{ ansible_env.HOME }}/.vim/{{ item }}.vim" state=link force=yes
  with_items:
          - "plugins"
          - "config"

- name: "Downloading Vundle for Vim"
  become: yes
  become_user: dgarcia
  git: repo="https://github.com/VundleVim/Vundle.vim.git" dest={{ansible_env.HOME}}/.vim/bundle/Vundle.vim update=no

- name: "Installing Vim Plugins"
  shell: vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa
  args:
    creates: "{{ansible_env.HOME}}/.vim/bundle/YouCompleteMe"

- name: "Installing Vim Plugin: YouCompleteMe"
  shell: "{{ansible_env.HOME}}/.vim/bundle/YouCompleteMe/install.py"
  args:
    creates: "{{ansible_env.HOME}}/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/cregex/regex_2/"

- name: "Downloading fzf"
  git: repo="https://github.com/junegunn/fzf.git" dest={{ansible_env.HOME}}/.fzf update=no
- name: "Installing fzf"
  shell: "{{ansible_env.HOME}}/.fzf/install"
  args:
   creates: "{{ansible_env.HOME}}/.fzf/bin/fzf"

- name: "Downloading Bashmarks"
  git: repo="https://github.com/vecin2/bashmarks.git" dest={{ansible_env.HOME}}/.local/bashmarks update=no
- name: "Installing bashmarks"
  shell: chdir={{ansible_env.HOME}}/.local/bashmarks make install
 
- name: "Installing python3 virtualenvwrapper"
  pip:
    executable=pip3
    name=virtualenvwrapper
