- name: "Downloading dot files"
  git: repo="https://github.com/vecin2/dotfiles.git" dest={{ansible_env.HOME}}/dotfiles update=no

- name: "Link Dotfiles"
  file: src="{{ ansible_env.HOME }}/dotfiles/{{ item }}" dest="{{ ansible_env.HOME }}/.{{ item }}" state=link force=yes
  with_items:
          - "flake8"
          - "profile"
          - "pylintrc"

- name: "Installing python3 virtualenvwrapper for user"
  shell: pip3 install virtualenvwrapper --user
  args:
    creates: "{{ansible_env.HOME}}/.local/bin/virtualenvwrapper.sh"

- name: Clear ~/.bash_ansible
  copy:
    content: ""
    dest: "{{ansible_env.HOME}}/.bash_ansible"
    force: yes

- name: "Configuring virtualenvwrapper in bash_ansible"
  blockinfile:
    path : "{{ansible_env.HOME}}/.bash_ansible"
    marker: "#{mark} virtualwrapper"
    create: yes
    block: |
      export WORKON_HOME=$HOME/.virtualenvs
      export PROJECT_HOME=$HOME/dev/python
      export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3.6
      source $HOME/.local/bin/virtualenvwrapper.sh

- name: "Check if pywinrm is installed"
  find:
    path: "/usr/local/lib/python2.7/dist-packages"
    patterns: "pywinrm*"
    file_type: directory
  register: pywinrm_files

- name: "pip install pywinrm if is not installed"
  become: yes
  shell: pip install pywinrm
  when: pywinrm_files.matched ==0

- name: "pip install black"
  become: yes
  shell: python3 -m pip install black

- name: "pip install isort"
  become: yes
  shell: python3 -m pip install isort

- name: "pip install flake8"
  become: yes
  shell: python3 -m pip install isort

- name: "pip install ropevim"
  become: yes
  shell: python3 -m pip install ropevim
