- name: "Downloading dot files"
  git: repo="https://github.com/vecin2/dotfiles.git" dest={{ansible_env.HOME}}/dotfiles update=no

- name: "Link Dotfiles"
  file: src="{{ ansible_env.HOME }}/dotfiles/{{ item }}" dest="{{ ansible_env.HOME }}/.{{ item }}" state=link force=yes
  with_items:
          - "bashrc"
          - "bash_aliases"
          - "flake8"
          - "gitconfig"
          - "vimrc"
          - "profile"
          - "pylintrc"
          - "tmux.conf"

- name: "Create .vim folder"
  file:
    path: "{{ ansible_env.HOME}}/.vim"
    state: directory

- name: "Link Vim files"
  file: src="{{ ansible_env.HOME }}/dotfiles/vim/{{ item }}.vim" dest="{{ ansible_env.HOME }}/.vim/{{ item }}.vim" state=link force=yes
  with_items:
          - "plugins"
          - "config"

- name: "Downloading Vundle for Vim"
  git: repo="https://github.com/VundleVim/Vundle.vim.git" dest={{ansible_env.HOME}}/.vim/bundle/Vundle.vim update=no

- name: "Installing Vim Plugins"
  shell: vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa
  args:
    creates: "{{ansible_env.HOME}}/.vim/bundle/YouCompleteMe"

- name: "Patching nerdtree-git-plugin"
  copy:
    src: "{{ansible_env.HOME}}/dev/ansible/ws_playbook/tasks/git_status.vim"
    dest: "{{ansible_env.HOME}}/.vim/bundle/nerdtree-git-plugin/nerdtree_plugin/git_status.vim"
- name: "Installing Vim Plugin: YouCompleteMe"
  shell: "{{ansible_env.HOME}}/.vim/bundle/YouCompleteMe/install.sh"
  args:
    creates: "{{ansible_env.HOME}}/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/cregex/regex_2/_regex.so"


- name: "Installing python3 virtualenvwrapper for user"
  shell: pip3 install virtualenvwrapper --user
  args:
    creates: "{{ansible_env.HOME}}/.local/bin/virtualenvwrapper.sh"

- name: Clear ~/.bash_ansible
  copy:
    content: ""
    dest: "{{ansible_env.HOME}}/.bash_ansible"
    force: yes

- name: "Configuring virtualenvwrapper in bash_ansible"
  blockinfile:
    path : "{{ansible_env.HOME}}/.bash_ansible"
    marker: "#{mark} virtualwrapper"
    create: yes
    block: |
      export WORKON_HOME=$HOME/.virtualenvs
      export PROJECT_HOME=$HOME/dev/python
      export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3.6
      source $HOME/.local/bin/virtualenvwrapper.sh

- name: "Check if pywinrm is installed"
  find:
    path: "/usr/local/lib/python2.7/dist-packages"
    patterns: "pywinrm*"
    file_type: directory
  register: pywinrm_files

- name: "pip install pywinrm if is not installed"
  become: yes
  shell: pip install pywinrm
  when: pywinrm_files.matched ==0

- name: "pip install black"
  become: yes
  shell: python3 -m pip install black

- name: "pip install isort"
  become: yes
  shell: python3 -m pip install isort

- name: "pip install flake8"
  become: yes
  shell: python3 -m pip install isort

- name: "pip install ropevim"
  become: yes
  shell: python3 -m pip install ropevim
