---
- name: Adding fasd apt repository
  become: true
  apt_repository:
    repo: ppa:aacebedo/fasd
    state: present

- name: Install fasd
  become: true
  apt:
    name: fasd

- name: Source fasd on rc files
  blockinfile:
    path: '{{myshellrc}}'
    marker: '#{mark} fasd config'
    block: |
      #It caches the initialization for minimal overhead
      fasd_cache="$HOME/.fasd-init-bash"
      if [ "$(command -v fasd)" -nt "$fasd_cache" -o ! -s "$fasd_cache" ]; then
        fasd --init posix-alias bash-hook bash-ccomp bash-ccomp-install >| "$fasd_cache"

      fi
      source "$fasd_cache"
      unset fasd_cache
