---
- name: "Downloading fzf"
  ansible.builtin.git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: "{{ ansible_env.HOME }}/.fzf"
    update: false
  tags:
    - fzf

- name: "Installing fzf"
  ansible.builtin.command: "{{ ansible_env.HOME }}/.fzf/install --all"
  args:
    creates: "{{ ansible_env.HOME }}/.fzf/bin/fzf"
  tags:
    - fzf

- name: "Configuring fzf"
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.fzf.{{ myshell }}"
    create: true
    marker: "#{mark} Custom Configuration"
    block: source "{{ playbook_dir }}/files/fzf_custom.bash"
  tags:
    - fzf

- name: "Source fzf.bash on rc files"
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    line: "[ -f ~/.fzf.bash ] && source ~/.fzf.bash"
    state: present
  tags:
    - fzf
