- name: "Downloading fzf"
  git: repo="https://github.com/junegunn/fzf.git" dest={{ansible_env.HOME}}/.fzf update=no
- name: "Installing fzf"
  shell: "{{ansible_env.HOME}}/.fzf/install"
  args:
   creates: "{{ansible_env.HOME}}/.fzf/bin/fzf"

- name: "Link fzf.bash"
  file: src="{{ playbook_dir }}/files/fzf.bash" dest="{{ ansible_env.HOME }}/.fzf.bash" state=link force=yes

- name: "Source fzf.bash on rc files"
  lineinfile:
    path: "{{ansible_env.HOME}}/.profile"
    line: "[ -f ~/.fzf.bash ] && source ~/.fzf.bash"
    state: present
