---
- name: "Installing git"
  become: true
  ansible.builtin.apt:
    name: git
- name: "Setting up personal gitconfig"
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/gitconfig/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item.split('.')[0] }}"
    state: link
    force: "yes"
  with_items:
    - gitconfig.linux

- name: "Setting multiple gitconfigs"
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/gitconfig/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item.split('.')[0] }}"
    state: link
    force: "yes"
  with_items:
    # - gitconfig.linux # this is useful for wsl to distinguish btw windows and wsl
    - gitconfig-personal
    - gitconfig-work
    #
- name: "Linking multiple gitconfig files on Windows host (WSL)"
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/gitconfig/{{ item }}"
    dest: "/mnt/c/Users/{{ win_username }}/.{{ item.split('.')[0] }}"
  with_items:
    # - gitconfig.win
    - gitconfig-personal
    - gitconfig-work
  when: "'WSL' in wsl_version"

- name: Setup SSH Config for Git
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/gitconfig/ssh_config"
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    state: link
    force: "yes"
  tags: git

- name: Adding git Aliases
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_aliases"
    line: source "{{ playbook_dir }}/files/gitconfig/git_aliases.sh"
    create: true
    regexp: '^source "{{ playbook_dir }}/files/gitconfig/git_aliases.sh"$'

- ansible.builtin.import_tasks: tasks/lazygit.yml
  tags: git
#- name: 'Start ssh agent on start'
#  blockinfile:
#    marker: '#{mark} ssh configuration'
#    path: '{{myshellrc}}'
#    content: |
#      if ! [ -z "${SSH_AGENT_PID}" ]
#      then
#        if ps -p $SSH_AGENT_PID > /dev/null
#        then
#          echo "ssh-agent is already running" > /dev/null
#        else
#          eval "$(ssh-agent -s)"
#          ssh-add ~/.ssh/id_ed25519_vecin2
#        fi
#      fi
#    create: true
#- name: 'Apply wsl2 git performance workaround'
#  blockinfile:
#    marker: '#{mark} git workaround on wsl2'
#    path: '{{myshellrc}}'
#    content: |
#      # checks to see if we are in a windows or linux dir
#      function isWinDir {
#        case $PWD/ in
#        /mnt/*) return $(true);;
#        *) return $(false);;
#        esac
#      }
#      # wrap the git command to either run windows git or linux
#      function git {
#        if isWinDir
#        then
#        git.exe "$@"
#        else
#        /usr/bin/git "$@"
#        fi
#      }
#    create: true
