---
- name: Create mount folders
  become: true
  ansible.builtin.file:
    path: "/mnt/{{ item }}"
    state: absent
    owner: root
    group: root
    mode: 777 #permission will be controlled from nas side
  loop:
    - PlexMedia
