- import_tasks: tasks/javadev/kse.yml
- import_tasks: tasks/javadev/jd_gui.yml
- import_tasks: tasks/javadev/eclipse.yml
- import_tasks: tasks/javadev/intellij.yml
- import_tasks: tasks/javadev/sdkman.yml
- import_tasks: tasks/javadev/maven.yml
