---
- name: "Installing cargo"
  become: true
  ansible.builtin.apt:
    name: cargo
- name: Add cargo to PATH
  ansible.builtin.lineinfile:
    path: "{{ myshellrc }}"
    regexp: ^export PATH=\"$HOME/.cargo
    line: export PATH="$HOME/.cargo/bin:$PATH"
    create: true
  tags: cargo

- name: Install "stylua" Rust package
  community.general.cargo:
    name: stylua
