- name: "Installing cargo"
  become: yes
  apt: name=cargo
- name: Add cargo to PATH
  lineinfile:
    path: '{{ansible_env.HOME}}/.profile'
    regexp: ^export PATH=\"$HOME/.cargo
    line: export PATH="$HOME/.cargo/bin:$PATH"
    create: true
  tags: cargo
