#fixing ALE cursor issue:
#sudo apt-get install software-properties-common
#sudo add-apt-repository ppa:jonathonf/vim
#sudo apt install vim
- name: "Installing other packages"
  become: yes
  apt:
    name:
      - python3-pip
      - software-properties-common # Part of the fix for ALE not highlighting cursor when error line
