- name: "Installing Packages"
  become: true
  become_user: root
  apt: 
    name:
      - git
      - tmux
      - tmuxinator
      - xclip
      - ack
      - python3-pip
      - cmake
      - vim-gtk
      - silversearcher-ag

