- name: Configure my bash functions
  blockinfile:
    path: "{{myshellrc}}"
    marker: "#{mark} mybash functions"
    content: |
      google() {
        search=""
        echo "Googling: $@"
        for term in $@; do
          search="$search%20$term"
        done
        chrome "http://www.google.com/search?q=$search"
      }
