- name: Configure my bash functions
  blockinfile:
    path: "{{ansible_env.HOME}}/.bashrc"
    marker: "#{mark} mybash functions"
    content: |
      google() {
        search=""
        echo "Googling: $@"
        for term in $@; do
          search="$search%20$term"
        done
        firefox "http://www.google.com/search?q=$search"
      }

- name: Configuring General Environment Variables
  blockinfile:
    path: '{{myshellrc}}'
    marker: '#{mark} General ENV VARS'
    block: |
      export DOWNLOADS=/mnt/c/Users/dgarcia/Downloads
