---
- name: Create nvim app folder
  become: true
  ansible.builtin.file:
    path: "/opt/nvim"
    state: directory
  tags: nvim

- name: Download nightly nvim
  become: true
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux-x86_64.appimage
    dest: "/opt/nvim"
    mode: '0755'
  tags: nvim

- name: Ensure nvim is linked as vim
  become: true
  ansible.builtin.file:
    src: "/opt/nvim/nvim-linux-x86_64.appimage"
    dest: /usr/local/bin/vim
    state: link
    force: true
  tags: nvim

- name: Install Fuse For Running nvim image
  become: true
  ansible.builtin.apt:
    name: libfuse2t64 #fuse conflicts with fuse3
    state: present

- name: Create nvim configfolder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory
  tags: nvim

- name: Creating nvim symlinks
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/nvim/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/nvim/{{ item }}"
    state: link
    force: "yes"
  with_items:
    - init.lua
    - lua
  tags: nvim

- name: Creating common nvim symlinks -config and plugins
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/vim/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/nvim/{{ item }}"
    state: link
    force: "yes"
  with_items:
    - config.vim
    - plugins.vim
  tags: nvim

- name: Setting aliases for nvim
  ansible.builtin.blockinfile:
    marker: "#{mark} nvim aliases"
    path: "{{ ansible_env.HOME }}/.bash_aliases"
    content: |
      alias nvim=~/apps/nvim/nvim.appimage
      alias vimdiff='nvim -d'
      alias vim='nvim'
    create: true
  tags: nvim
- name: Bash configuration for Vim
  ansible.builtin.blockinfile:
    path: "{{ myshellrc }}"
    marker: "#{mark} Vim vars"
    block: |
      #This var is use in VIM mapping which opens docs in CLOUD folder
      export CLOUD_LOC=$HOME/gdrive
      export DOT_FILES_LOC={{ playbook_dir }}
      #Free Ctrl-s and Ctrl-q so it can be used in terminal apps (vim)
      stty -ixon
  tags: nvim
