---
- name: Add nodejs apt key
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add nodejs 17.x ppa for apt repo
  become: true
  apt_repository:
    repo: deb https://deb.nodesource.com/node_17.x bionic main

#if fails do it manually: ws_playbook$curl -sL https://deb.nodesource.com/setup_17.x | sudo -E bash -
# curl -sL https://deb.nodesource.com/setup_17.x | sudo -E bash -
# sudo apt install nodejs
- name: Install nodejs
  become: true
  apt:
    update_cache: true
    force: true
    name: nodejs
    state: present
  tags: nodejs
