- name: "Add nodejs apt key"
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  tags: nodejs

- name: "Add nodejs ppa for apt repo"
  become: true
  vars: 
    nodejs_version: 17
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{nodejs_version}}.x {{ansible_lsb.codename }} main
    update_cache: yes
  tags: nodejs

- name: "Install nodejs"
  become: true
  apt:
    update_cache: yes
    name: nodejs
    state: present
  tags: nodejs
