- name: Install Node.js dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - software-properties-common

- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    state: present

- name: "Add nodejs ppa for apt repo"
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{node_version}} nodistro main"
    update_cache: yes
    filename: nodesource

- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present
      
      #- name: Install build-essential
      #  apt:
      #    name: build-essential
      #    state: present
