---
- name: Installing other basic packages
  become: true
  apt:
    name:
      - xclip
      - cmake #used by YouCompleteMe (vim plugin)
        #- npm # used to install wsl-open

- name: Installing Ubuntu python-is-python3 on 20.04
  apt:
    name:
      - python-is-python3 #so scripts starting with '/usr/bin/env python' can be run in unbuntu 20.04
  when: ansible_lsb.id == 'Ubuntu' and ansible_lsb.release == '20.04' and 'WSL' in wsl_version
  tags: WSL

- name: Install "wsl-open" node.js package.
  become: true
  npm:
    name: wsl-open
    path: '{{ansible_env.HOME}}/.local/'
    state: present
    global: true
  tags: wsl-open

- name: Setting alias 'wo' for wsl-open
  lineinfile:
    path: '{{ansible_env.HOME}}/.bash_aliases'
    line: alias wo="wsl-open"
    create: true
