---
- name: Install packages
  win_chocolatey:
    name: "{{ item }}"
    state: present
  loop:
  - 'git'
  - 'vim'
  - 'googlechrome'
    #- name: Installing virtualenvwrapper-win
    #  pip:
    #    name: Numpy
