---
- debug:
    var: ansible_connection
<<<<<<< HEAD
=======
- debug: var=hostvars[inventory_hostname]['ansible_python_interpreter']
>>>>>>> 5d10504249aa5209335d42e7c08405e76c31e35d
- name: Install packages
  win_chocolatey:
    name: "{{ item }}"
    state: present
  loop:
  - 'git'
  - 'vim'
  - 'skype'
  - 'google-backup-and-sync'
  - '7zip'
  - 'python3'
  - 'VcXsrv'
- name: Install python virtualenvwrapper-win
  win_command: python -m pip install virtualenvwrapper-win
- name: Install python Cython
  win_command: python -m pip install Cython

