---
- name: Add Python repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: "Installing python apt packages"
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items: "{{python_apt_packages}}"

- name: "Installing python pip packages"
  become: yes
  ansible.builtin.pip:
    name: "{{item}}"
  with_items: "{{python_pip_packages}}"

# Do not auto install pyenv, because we prefer to install it manually so we can install ansible in virtualenv
# also the role did not work well with zsh completions
# - ansible.builtin.import_tasks: tasks/pythondev/pyenv.yml
  # tags: pyenv
- ansible.builtin.import_tasks: tasks/pythondev/virtualenvwrapper.yml
- ansible.builtin.import_tasks: tasks/pythondev/pythonvim_IDE.yml
