- name: Add Python repository into sources list
  become: yes
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: "Installing python apt packages"
  become: yes
  apt:
    name: "{{item}}"
  with_items: "{{python_apt_packages}}"

- name: "Installing python pip packages"
  become: yes
  ansible.builtin.pip:
    name: "{{item}}"
  with_items: "{{python_pip_packages}}"

- import_tasks: tasks/pythondev/virtualenvwrapper.yml
- import_tasks: tasks/pythondev/pythonvim_IDE.yml
