- name: Add Python repository into sources list
  become: yes
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: "Installing python packages"
  become: yes
  apt:
    name:
      - python3-pip
      - python3.8-venv #require by pylsp
      - python3.10

- import_tasks: tasks/pythondev/virtualenvwrapper.yml
- import_tasks: tasks/pythondev/pythonvim_IDE.yml
