---
- name: Installing ack, ag and ripgrep
  become: true
  ansible.builtin.apt:
    name:
      - ack
      - silversearcher-ag
      - ripgrep
      - fd-find

- name: "Setting alias for silversearcher"
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_aliases"
    line: "alias ag=\"ag --color-path '36;1' --color-line-number '1;35'\""
    create: true
- name: Ensures ~/.local/bin dir exists
  ansible.builtin.file:
    path: ~/.local/bin
    state: directory
- name: "Setting fd alias for fdfind"
  ansible.builtin.file:
    src: /usr/bin/fdfind
    dest: ~/.local/bin/fd
    state: link
    force: "yes"
