---
- name: Set shell
  shell: echo $SHELL
  register: shell_output
  tags: shell
- debug: var=shell_output.stdout
  tags: shell
- debug: var=myshell
  tags: shell
- debug:
    msg: 'Running command: usermod --shell /bin/{{myshell}} dgarcia'
  tags: shell
- name: Updating shell
  become: true
  shell: usermod --shell /bin/{{myshell}} dgarcia
  register: usermod_output
  when: shell_output.stdout not in myshell
  tags: shell
- debug: var=usermod_output
  tags: shell

- name: Installing General Util Packages
  become: true
  package:
    name: "{{item}}"
  with_items: "{{shell_util_packages}}"

# - name: Create NAS mnt Folder
#   file:
#     path: '/etc/fstab/nas'
#     state: directory
#     recurse: true
#   tags: shell
#
# - name: Add NAS network Drive to Mount drive file
#   become: true
#   lineinfile:
#     path: '/etc/fstab'
#     regexp: ^N
#     line: "N: /mnt/nas drvfs defaults 0 0"
#     create: true
#   when:  "'WSL' in wsl_version"
#   register: mount_nas
#   tags: shell

# - name: Run mount command 
#   become: true
#   shell: mount -a
#   when: mount_nas.changed
