---
- name: Set shell
  ansible.builtin.shell: echo $SHELL
  register: shell_output
  tags: shell
- ansible.builtin.debug:
    var: shell_output.stdout
  tags: shell
- ansible.builtin.debug:
    var: myshell
  tags: shell
- ansible.builtin.debug:
    msg: "Running command: usermod --shell /bin/{{ myshell }} dgarcia"
  tags: shell

- name: Ensure ~/.bash_aliases exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.bash_aliases"
    state: touch
    mode: '0644'

- name: Updating shell
  become: true
  ansible.builtin.command: usermod --shell /bin/{{myshell}} dgarcia
  register: usermod_output
  when: shell_output.stdout not in myshell
  tags: shell
- ansible.builtin.debug:
    var: usermod_output
  tags: shell

- name: Installing General Util Packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
  with_items: "{{shell_util_packages}}"

# - name: Create NAS mnt Folder
#   file:
#     path: '/etc/fstab/nas'
#     state: directory
#     recurse: true
#   tags: shell
#
# - name: Add NAS network Drive to Mount drive file
#   become: true
#   lineinfile:
#     path: '/etc/fstab'
#     regexp: ^N
#     line: "N: /mnt/nas drvfs defaults 0 0"
#     create: true
#   when:  "'WSL' in wsl_version"
#   register: mount_nas
#   tags: shell

# - name: Run mount command
#   become: true
#   shell: mount -a
#   when: mount_nas.changed
