---
- name: Set shell
  shell: echo $SHELL
  register: shell_output
  tags: shell
- debug: var=shell_output.stdout
  tags: shell
- debug: var=myshell
  tags: shell
- debug:
    msg: 'Running command: usermod --shell /bin/{{myshell}} dgarcia'
  tags: shell
- name: Updating shell
  become: true
  shell: usermod --shell /bin/{{myshell}} dgarcia
  register: usermod_output
  when: shell_output.stdout not in myshell
  tags: shell
- debug: var=usermod_output
  tags: shell

- name: Installing General Util Packages
  become: true
  package:
    name: "{{item}}"
  with_items: "{{shell_util_packages}}"

