---
- name: Installing tmuxinator
  become: true
  ansible.builtin.apt:
    name:
      - git
      - tmuxinator

- name: Setting alias for tmuxinator
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_aliases"
    line: alias mux=tmuxinator
    create: true

- name: Adding custom tmuxinator functions

  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    marker: "#{mark} tmuxinator"
    content: |-
      muxworkon(){
        tmux kill-session  -t "dummy"
        tmuxinator list-sessions || ( tmux new -d -s "dummy" && tmuxinator start $1 )
      }
