---
- name: Install tmux package
  become: true
  ansible.builtin.package:
    name: tmux

- name: Link tmux.conf
  ansible.builtin.file:
    src: "{{ playbook_dir }}/files/tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    state: link
    force: "yes"
  tags: tmux

- name: "Configure shell on .tmux"
  ansible.builtin.blockinfile:
    marker: "#{mark} tmux shell"
    path: "{{ ansible_env.HOME }}/.tmux.conf"
    content: |
      set-option -g default-shell /bin/{{ myshell }}
    create: true
  tags: tmux

- name: Setting alias for tmux new session start  with zsh
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: alias tnew="tmux new-session /bin/zsh \;"
    create: true
  when: myshell == 'zsh'
# - name: Auto-open Tmux on zsh - install tmux plugin (1/2)
#   ansible.builtin.lineinfile:
#     path: ~/.zshrc
#     regexp: '^plugins=\((.*)\)'
#     line: 'plugins=(\1 tmux)'
#     backrefs: yes
#     state: absent
#   tags: tmux

# - name: Auto-open Tmux on zsh - configure tmux plugin (2/2)
#   ansible.builtin.blockinfile:
#     path: ~/.zshrc
#     marker: "#{mark} Configure TMUX plugin"
#     insertafter: "plugins=(.*)"
#     block: |
#       ZSH_TMUX_AUTOSTART=true
#   tags: tmux
