---
- name: Uninstalling tmux
  become: true
  ansible.builtin.apt:
    name: tmux
    state: absent
  tags: tmux

- name: Installing tmux require packages
  become: true
  ansible.builtin.apt:
    name: # require to build tmux from tar file
      - libevent-dev
      - libncurses5-dev
      - libncursesw5-dev
  tags: tmux

- name: Create directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/tmux_installer"
    state: directory
  tags: tmux

- name: Downloading  tmux 3.3 from releases
  ansible.builtin.get_url:
    url: "https://github.com/tmux/tmux/releases/download/3.3a/tmux-3.3a.tar.gz"
    dest: "{{ ansible_env.HOME }}/tmux_installer/"
  tags: tmux

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: "{{ playbook_dir }}/files/install_tmux.sh"
    mode: "764"
  tags: tmux

- name: Install and config tmux from source
  ansible.builtin.command:
    cmd: "{{ playbook_dir }}/files/install_tmux.sh"
  tags: tmux
