---
- name: Configure EM aliases
  blockinfile:
    path: '{{ansible_env.HOME}}/.bash_aliases'
    marker: '#{mark} EM aliases'
    content: |
      alias tad="cd $EM_CORE_HOME"
      alias ced='wstart ccadmin ced'
      alias rsql='sqltask run-sql'
      alias csql='sqltask create-sql'
      alias tsql='sqltask create-sql'

- name: EM environment variables
  blockinfile:
    path: '{{ansible_env.HOME}}/.profile'
    marker: '#{mark} EM file'
    block: >
      [ -s "$HOME/.em.sh" ] && source "$HOME/.em.sh"
      # Load EM into a shell session *as a function*

- name: Link em.sh
  file: src="{{ playbook_dir }}/files/em.sh" dest="{{ ansible_env.HOME }}/.em.sh"
    state=link force=yes
