---
- name: Ensure fonts directory
  ansible.builtin.file:
    path: "{{ fonts_installation_path }}"
    state: directory

- name: Check FiraCode exists
  ansible.builtin.shell: "ls {{fonts_installation_path}}/FiraCode*Nerd*Font*"
  register: firacode_exists
  ignore_errors: true

- name: Download FiraCode Font
  when: firacode_exists is failed
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/FiraCode.zip
    dest: "{{ fonts_installation_path }}"
    remote_src: true

