---
- name: Link wsl.sh
  file:
    src="{{ playbook_dir }}/files/wsl/wsl.sh" dest="{{ ansible_env.HOME }}/.wsl.sh"
    state=link force=yes
  tags: wsl_integration

- name: Sourcing on shellrc file
  lineinfile:
    path: '{{myshellrc}}'
    line: '[ -s "$HOME/.wsl.sh" ] && source "$HOME/.wsl.sh"'
  tags: wsl_integration

- name: Setting alias 'chrome' for opening chrome
  lineinfile:
    path: '{{ansible_env.HOME}}/.bash_aliases'
    line: alias chrome="/mnt/c/Program\ Files/Google/Chrome/Application/chrome.exe" 
    create: true
  tags: wsl_integration

- name: Configure windows env vars 
  blockinfile:
    path: '{{myshellrc}}'
    marker: '#{mark} Add Windows Env Vars'
    block: |
      export WHOME="/mnt/c/Users/$USER"
      export DOWNLOADS=/mnt/c/Users/dgarcia/Downloads
  tags: wsl_integration

- name: Install "wsl-open" node.js package.
  become: true
  npm:
    name: wsl-open
    path: '{{ansible_env.HOME}}/.local/'
    state: present
    global: true
  tags: wsl-open

- name: Setting alias 'wo' for wsl-open
  lineinfile:
    path: '{{ansible_env.HOME}}/.bash_aliases'
    line: alias wo="wsl-open"
    create: true
