---
- shell: grep "^$USER" /etc/passwd
  register: shell_used #determine if bash or zsh
  tags: wsl_clipboard

- name: Set DISPLAY var
  vars:
    wsl1_display: localhost:0
    wsl2_display: $(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
    display: "{% if wsl_version == 'WSL1' %}
                {{wsl1_display}} 
              {%else%} 
                {{wsl2_display}}
              {% endif %}"
  lineinfile:
    path: '{{myshellrc}}'
    regexp: '^export DISPLAY='
    line: export DISPLAY={{display.strip()}}
  tags: wsl_clipboard

