---
- name: Setting WSL facts
  shell: |
    if [[ {{ansible_kernel}} == *'microsoft'* ]]; then
        echo "WSL2"
    elif [[ {{ansible_kernel}} == *'Microsoft'* ]]; then
        echo "WSL1"
    else
        echo "NO_WSL"
    fi
  args:
    executable: "/bin/bash"
  tags: always
  register: wsl_version_checker

- set_fact:
    wsl_version: "{{wsl_version_checker.stdout}}"
  tags: always
