#fixing ALE cursor issue:
#sudo apt-get install software-properties-common
#sudo add-apt-repository ppa:jonathonf/vim
#sudo apt install vim
- name: 'Installing python3 virtualenvwrapper for user'
  pip:
    name: virtualenvwrapper
    extra_args: --user

- include: tasks/pythondev/flake8.yml

- name: 'pip installing packages for VIM python IDE experience'
  become: yes
  pip:
    name:
      - black
      - pyls-isort
      - ropevim
      #- software-properties-common # Part of the fix for ALE not highlighting cursor when error line
