# - name: "Installing python3 virtualenvwrapper for user"
#   pip:
#     name: virtualenvwrapper
#     extra_args: --user
#   tags: python

- name: "Installing apt python3-virtualenvwrapper packages"
  become: yes
  apt:
    name: python3-virtualenvwrapper #install it as pip package fails with error: externally-managed-environment
  tags: python
  


- name: "Configuring virtualenvwrapper"
  blockinfile:
    path : "{{myshellrc}}"
    marker: "#{mark} virtualwrapper"
    create: yes
    block: |
      export WORKON_HOME=$HOME/.virtualenvs
      export PROJECT_HOME=$HOME/dev/python
      export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
      #source $HOME/.local/bin/virtualenvwrapper.sh
  tags: python
