---
# - name: "Installing python3 virtualenvwrapper for user"
#   pip:
#     name: virtualenvwrapper
#     extra_args: --user
#   tags: python

- name: "Installing apt python3-virtualenvwrapper packages"
  become: true
  ansible.builtin.apt:
    name: python3-virtualenvwrapper #install it as pip package fails with error: externally-managed-environment
  tags: python

- name: "Configuring virtualenvwrapper"
  ansible.builtin.blockinfile:
    path: "{{ myshellrc }}"
    marker: "#{mark} virtualwrapper"
    create: true
    block: |
      export WORKON_HOME=$HOME/.virtualenvs
      export PROJECT_HOME=$HOME/dev/python
      export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
      #source $HOME/.local/bin/virtualenvwrapper.sh
  tags: python
