- name: "Installing python3 virtualenvwrapper for user"
  pip:
    name: virtualenvwrapper
    extra_args: --user

- name: "Configuring virtualenvwrapper"
  blockinfile:
    path : "{{ansible_env.HOME}}/.profile"
    marker: "#{mark} virtualwrapper"
    create: yes
    block: |
      export WORKON_HOME=$HOME/.virtualenvs
      export PROJECT_HOME=$HOME/dev/python
      export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
      source $HOME/.local/bin/virtualenvwrapper.sh
