- name: "Computing wsltty themes path"
  shell: >
     wslpath "{{ansible_env['APPDATA']}}/wsltty/themes"
  register: themes_path

- name: "Configure gruvbox.minttyrc file in wsltty themes folder"
  file: src="{{ playbook_dir }}/files/gruvbox.minttyrc" dest="{{ themes_path.stdout}}" state=link force=yes
